MyArtGallery/Models/Message.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Web;
using MyArtGallery.Resources;

namespace MyArtGallery.Models
{
    public class Message
    {
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        public int MessageId { get; set; }
        [ForeignKey("Author")]
        public string AuthorId { get; set; }
        [ForeignKey("Addressee")]
        public string AddresseeId { get; set; }
        [Display(Name = "From", ResourceType = typeof(MessagesAndNotes))]
        public virtual UserProfile Author { get; set; }
        [Display(Name = "To", ResourceType = typeof(MessagesAndNotes))]
        public virtual UserProfile Addressee { get; set; }
        [Display(Name = "MessageTitle", ResourceType = typeof(MessagesAndNotes))]
        [StringLength(100, ErrorMessageResourceType = typeof(MessagesAndNotes),
              ErrorMessageResourceName = "MessageTitleLong")]
        public string Title { get; set; }
        [Display(Name = "Message", ResourceType = typeof(MessagesAndNotes))]
        [Required(ErrorMessageResourceType = typeof(MessagesAndNotes),
              ErrorMessageResourceName = "MessageRequired")]
        [StringLength(500, ErrorMessageResourceType = typeof(MessagesAndNotes),
              ErrorMessageResourceName = "MessageLong")]
        public string Text { get; set; }
        [Display(Name = "MessageDate", ResourceType = typeof(MessagesAndNotes))]
        [DataType(DataType.Date)]
        public DateTime SentDate { get; set; }
        [Display(Name = "WasRead", ResourceType = typeof(MessagesAndNotes))]
        public bool WasRead { get; set; }
        [ForeignKey("Parent")]
        [Display(Name = "ParentMessage", ResourceType = typeof(MessagesAndNotes))]
        public int? ParentId{ get; set; }
        public virtual Message Parent{ get; set; }
    }
}

MyArtGallery/Controllers/MessageController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using MyArtGallery.Models;
using Microsoft.AspNet.Identity;
using Microsoft.AspNet.Identity.EntityFramework;
using MyArtGallery.Resources;
using MyArtGallery.Repositories;
using System.Threading.Tasks;
using PagedList;
using MyArtGallery.App_Start;

namespace MyArtGallery.Controllers
{
    public class MessageController : BasicController
    {
        private IMessageRepository messagerepo;
        public UserManager<UserProfile> UserManager { get; private set; }
        public MessageController(UserManager<UserProfile> userManager, MessageRepository repo)
        {
            UserManager = userManager;
            messagerepo = repo;
        }

        public MessageController()
            : this(new UserManager<UserProfile>(new UserStore<UserProfile>(new MyArtGalleryContext())), new MessageRepository())
        {
        }

        [MyAuthenticationFilter]
        public async Task<ActionResult> Details(int? id)
        {
            if (id == null)
                return RedirectToAction("Error", "Home", new { message = Errors.MessageNotFound });

            Message message = await messagerepo.getMessage(id);
            if (message == null)
                return RedirectToAction("Error", "Home", new { message = Errors.MessageNotFound });

            if (message.Addressee.UserName.Equals(User.Identity.Name))
            {
                if (!message.WasRead)
                {
                    await messagerepo.SignAsRead(message);

                }
                return View(message);
            }
            try
            {
                if (message.Author.UserName.Equals(User.Identity.Name))
                    return View(message);
            }
            catch
            {
            }
            return RedirectToAction("Error", "Home", new { message = Errors.PrivacyViolation });


        }

        [MyAuthenticationFilter]
        public async Task<ActionResult> Delete(int? id)
        {
            if (id == null)
                return RedirectToAction("Error", "Home", new { message = Errors.MessageNotFound });

            Message message = await messagerepo.getMessage(id);
            if (message == null)
                return RedirectToAction("Error", "Home", new { message = Errors.MessageNotFound });

            return View(message);
        }

       [MyAuthenticationFilter]
        public ActionResult Send(string id)
        {
            Message model = new Message();
            UserProfile user = UserManager.FindByName(id);
            string name = User.Identity.GetUserName();

            if (user == null)
                return RedirectToAction("Error", "Home", new { message = Errors.UserNotFound });

            model.AddresseeId = user.UserName;
            model.AuthorId = name;
            model.SentDate = DateTime.Now;

            return View(model);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Send(Message model)
        {

            Message message = new Message {AuthorId = model.AuthorId, AddresseeId = model.AddresseeId, SentDate = model.SentDate, Text = model.Text, Title = model.Title };
          
            if (ModelState.IsValid)
            {
                
                await messagerepo.AddMessage(message);
                return RedirectToAction("Index", "Home");
            }

            return View(message);
        }

        [MyAuthenticationFilter]
        [HttpGet]
        public async Task<ActionResult> Reply(int id)
        {
            Message parent = await messagerepo.getMessage(id);
            if (parent == null)
                return RedirectToAction("Error", "Home", new { message = Errors.MessageNotFound });
            string name = User.Identity.GetUserName();
            UserProfile user = await UserManager.FindByNameAsync(parent.AuthorId);
            if (user == null)
                return RedirectToAction("Error", "Home", new { message = Errors.MessageNotFound });
            Message model = new Message();
            model.AuthorId = name;
            model.AddresseeId = parent.AuthorId;
            model.ParentId = parent.MessageId;
            model.Parent = parent;
            model.SentDate = DateTime.Now;

                 return View(model);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Reply(Message model)
        {
         
            Message message = new Message { AuthorId = model.AuthorId, AddresseeId = model.AddresseeId, ParentId=model.ParentId, SentDate = model.SentDate, Text = model.Text, Title = model.Title };
            Message parent = await messagerepo.getMessage(model.ParentId);
            string text = Resource.ReplyFor + parent.Title + " " + parent.SentDate.ToString()+". ";
            message.Text = text + model.Text;
            if (ModelState.IsValid)
            {

                await messagerepo.AddMessage(message);
                return RedirectToAction("SentList", "Message");
            }

            return View(model);
        }

        [MyAuthenticationFilter]
        public ActionResult SentList(int? page)
        {
            IQueryable<Message> messages = messagerepo.SentMessages(User.Identity.Name).AsQueryable().OrderByDescending(m => m.SentDate);
            int pagenumber = (page ?? 1);
            return View(messages.ToPagedList(pagenumber, 25));
        }

        [MyAuthenticationFilter]
        public ActionResult ReceivedList(int? page)
        {
            IQueryable<Message> messages = messagerepo.ReceivedMessages(User.Identity.Name).AsQueryable().OrderByDescending(m => m.SentDate);
            int pagenumber = (page ?? 1);
            return View(messages.ToPagedList(pagenumber,25));
        }


    
    }
}

MyArtGallery/Controllers/UserProfileController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using MyArtGallery.Models;
using Microsoft.AspNet.Identity;
using Microsoft.AspNet.Identity.EntityFramework;
using System.Threading.Tasks;
using Microsoft.Owin.Security;
using System.Security.Claims;
using System.Web.Helpers;
using MyArtGallery.Models.Helpers;
using MyArtGallery.Repositories;
using System.IO;
using MyArtGallery.Models.UserViewModels;
using PagedList;
using System.Drawing;
using System.Drawing.Imaging;
using MyArtGallery.Resources;
using MyArtGallery.Helpers;
using System.Net.Mail;
using MyArtGallery.Services;
using MyArtGallery.Validation;
using MyArtGallery.App_Start;

namespace MyArtGallery.Controllers
{
    public class UserProfileController : BasicController
    {
        private IUserAccountService user_service;
        public UserProfileController()
        {
            user_service = new UserAccountService(new ModelStateExtension(this.ModelState));
        }
        public UserProfileController(IUserAccountService s)
        {
            user_service = s;
        }
        public ActionResult List(int? page)
        {
            IQueryable<UserProfile> lista = user_service.UserManager.Users.OrderByDescending(u=>u.UserName);
            int pagenumber = (page ?? 1);
            return View(lista.ToPagedList(pagenumber, 10));
        }

        [HttpGet]
        [AllowAnonymous]
        public ActionResult Login(string url, string message)
        {
            LoginViewModel model = new LoginViewModel();
            model.Message = message;
            model.Url = url;
            return View(model);
        }
        [HttpPost]
        [AllowAnonymous]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Login(LoginViewModel model)
        {
            if (ModelState.IsValid)
            {
                UserProfile user = await user_service.UserManager.FindAsync(model.UserName, model.Password);
                UserProfile user1 = await user_service.UserManager.FindByNameAsync(model.UserName);
                if (user != null)
                {
                    if (user.AccessFailedCount < 3)
                    {

                        user.LockoutEndDateUtc = null;
                        user.AccessFailedCount = 0;
                        await user_service.UserManager.UpdateAsync(user);
                        await AsyncLogin(user, model.RememberMe);

                        if (string.IsNullOrEmpty(model.Url))
                            return RedirectToAction("Index", "Home");
                        else
                            return Redirect(model.Url);
                    }
                    else if (user.LockoutEnabled && user.LockoutEndDateUtc < DateTime.UtcNow)
                    {
                        user.LockoutEndDateUtc = null;
                        user.LockoutEnabled = false;
                        user.AccessFailedCount = 0;
                        await user_service.UserManager.UpdateAsync(user);
                        await AsyncLogin(user, model.RememberMe);
                        return RedirectToAction("Index", "Home");
                    }
                    else
                    {
                        ModelState.AddModelError("Password", UserAccount.LimitPassed);
                    }
                }
                else if (user1 != null)
                {
                    user1.AccessFailedCount += 1;
                    user1.LockoutEnabled = true;
                    user1.LockoutEndDateUtc = DateTime.UtcNow.AddHours(12);
                    await user_service.UserManager.UpdateAsync(user1);
                    ModelState.AddModelError("Password", UserAccount.LoginError);
                }
                else
                {
                    ModelState.AddModelError("UserName", UserAccount.UserNameError);                  
                }
            }

             //w razie błędu
            return View(model);
        }

        [AllowAnonymous]
        public ActionResult Register()
        {
            Random r = new Random();
            int A = r.Next(0, 21);
            int B = r.Next(0, 21);
            RegistrationViewModel model = new RegistrationViewModel();
            model.A = A;
            model.B = B;
            model.Answer = A + B;
            model.Gender = Gender.N;
            string culture = RouteData.Values["culture"] as string;
            model.Genres = user_service.CategoriesSelect(culture);
            return View(model);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        [AllowAnonymous]
        public async Task<ActionResult> Register(RegistrationViewModel model)
        {
            CreateAvatarDirectory();
            DeleteTemps();
            CreateUserFolders(model.UserName);
            Image img = null;
            string ext = ".png";
            bool validType = false;
            string proto_path = @"~/Images/Avatars/Temp/";
            if (model.IsUrl)
            {
                if (model.Url != null)
                {
                    if (validType)
                    {
                        validType = user_service.ValidAvatar(model.Url, true);
                        ext = ImageHelper.GetFileType(model.Url);
                        proto_path += model.UserName +ext;
                        ImageHelper.SaveImageProto(model.Url, Request.MapPath(proto_path));
                    }
                }
                else
                {
                    validType = user_service.ValidAvatar("",true);
                }
            }
            else
            {
                if (model.File != null)
                {
                    validType = user_service.ValidAvatar(model.File.FileName, false);
                    ext = Path.GetExtension(model.File.FileName);
                    if (validType)
                    {
                        proto_path += model.UserName +ext;
                        ImageHelper.SaveImageProto(model.File, Request.MapPath(proto_path));
                    }
                }
                else
                {
                    validType = user_service.ValidAvatar("", false);
                }
            }
            try
            {
                img = Image.FromFile(Request.MapPath(proto_path));
            }
            catch
            {
                img = null;
            }
            ImageHelper.DeleteImage(Request.MapPath(proto_path));
            if (user_service.UserManager.FindByName(model.UserName) != null)
                ModelState.AddModelError("UserName", UserAccount.UserExists);
            if (model.Answer != model.Result)
                ModelState.AddModelError("Result", UserAccount.HumanValidation);
           
            if (ModelState.IsValid)
            {
                var user = new UserProfile() { UserName = model.UserName, Email = model.Email, BirthDate = (DateTime)model.BirthDate, Country = model.Country, Rank = Rank.User, UserDescription = model.UserDescription, Gender = model.Gender, Albums = new List<Album> { }, Comments = new List<Comment> { } };
                string[] path = UserProfileHelper.SetAvatarPath(img, model.UserName);
                user.AvatarPath = path[0];
                user.AvatarThumbPath = path[1];             
                List<Category> genres = await user_service.SelectedCategories(model.SelectedGenres).ToListAsync();
                user.Genres = genres;
                user.Favourites = new List<Favourite> { };
                Album def = new Album { UserName=user.UserName, Path = user.UserName, Pictures = new List<Picture> { }, SubAlbums = new List<Album> { }, Title="Default", AddedDate=DateTime.Now, LastModifiedDate=DateTime.Now, Public=true };
                AlbumRepository repo = new AlbumRepository();
                IdentityResult result = await user_service.UserManager.CreateAsync(user, model.Password);
                await repo.AddAlbum(0, def);
                    if (result.Succeeded)
                    {
                        if (img != null)
                        {
                            img = ImageHelper.CreateImage(img, model.X, model.Y, model.Width, model.Height, 0, false, false);
                            Bitmap img1 = ImageHelper.ResizeImage(img, 150, 150);
                            Bitmap thumb = ImageHelper.ResizeImage(img, 50, 50);
                            img.Dispose();
                            img1.Save(Request.MapPath(path[0]), ImageFormat.Png);
                            thumb.Save(Request.MapPath(path[1]), ImageFormat.Png);
                            ImageHelper.DeleteImage(proto_path);
                        }
                        await AsyncLogin(user, isPersistent: false);
                        return RedirectToAction("Index", "Home");
                    }
            }
            // jak są błędy
            ImageHelper.DeleteImage(proto_path);
            Random r = new Random();
            int A = r.Next(0, 21);
            int B = r.Next(0, 21);
            model.A = A;
            model.B = B;
            model.Answer = A + B;
            model.Gender = Gender.N;
            string culture = RouteData.Values["culture"] as string;
            model.Genres = user_service.CategoriesSelect(culture);
            model.SelectedGenres = null;
            model.Gender = Gender.N;
            return View(model);
        }

        public async Task<ActionResult> Browse(string id)
        {
            if (id == null)
                return RedirectToAction("Error", "Home", new { message = Errors.UserNotFound });
            UserProfile user = await user_service.UserManager.FindByNameAsync(id);
            if (user == null)
                return RedirectToAction("Error", "Home", new { message = Errors.UserNotFound });

MyArtGallery/Views/Message/Details.cshtml
@model MyArtGallery.Models.Message
@using MyArtGallery.Resources;
@{
    ViewBag.Title = @MessagesAndNotes.Message;
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div>
    <h4>@MessagesAndNotes.Message</h4>
    <div class="message-frame">

        <div>
          @MessagesAndNotes.From  <b>@Html.DisplayFor(model => model.Author.UserName) </b>
        </div>
        <div>
          @MessagesAndNotes.To  <b>@Html.DisplayFor(model => model.Addressee.UserName) </b>
        </div>
        <div>
          <i>@Html.DisplayFor(model => model.SentDate)</i>
        </div>
        <div>
          @Html.DisplayFor(model => model.Title)
        </div>

        <div>
            
            @Html.DisplayFor(model => model.Text)
        </div>
       @if(Model.ParentId!=null){
            @Html.ActionLink(@Resource.ReplyFor+ " "+ @MessagesAndNotes.Message + ": "+ @Model.Parent.AuthorId, "Details", "Message", new { id=Model.ParentId }, new{@class="links"})
          }
    </div>
</div>
<ul class="links"> 
  <li>@Html.ActionLink(@Resource.Reply, "Reply", new{id = Model.MessageId})</li>
 <li>@Html.ActionLink(@Resource.Back, "Messages", "UserProfile", new {id = User.Identity.Name}, null)</li>
</ul>

MyArtGallery/Views/Message/ReceivedList.cshtml
@model PagedList.IPagedList<MyArtGallery.Models.Message>
@using PagedList.Mvc;
@using MyArtGallery.Resources;
@{
    ViewBag.Title = @MessagesAndNotes.Messages;
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>@MessagesAndNotes.Messages</h2>
      @if (Model.Count() == 0)
      {
          <p>@MessagesAndNotes.NoMessages</p>
     }
<table id="message-list">
@foreach (var item in Model) {
    <tr>
        <td class="author-name">
           @if(item.WasRead==false){
             <b class="highlight">*</b>
           }
           @Html.DisplayFor(modelItem => item.Author.UserName)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Title)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Text)
            @Html.ActionLink(@Resource.Browse, "Details", new { id=item.MessageId })
     
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.SentDate)
        </td>
    </tr>
}

</table>
<div id="pager">
@Resource.Page @(Model.PageCount < Model.PageNumber ? 0 : Model.PageNumber) @Resource.Of @Model.PageCount

@Html.PagedListPager(Model, page => Url.Action("ReceivedList", new { page}), new PagedListRenderOptions{
                                                                        LinkToFirstPageFormat = "<<",
                                                                        LinkToPreviousPageFormat = @Resource.Prev,
                                                                        LinkToNextPageFormat = @Resource.Next,
                                                                        LinkToLastPageFormat = ">>",
                                                              })
</div>
<ul class="links">
<li>@Html.ActionLink(@MessagesAndNotes.SentMessages, "SentList")</li>
</ul>

MyArtGallery/Views/Message/Reply.cshtml
@model MyArtGallery.Models.Message
@using MyArtGallery.Resources;
@{
    ViewBag.Title = @Resource.ReplyFor;
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<div id="gallery-wrapper">
<div id="form-wrapper">

 <div>
   <h2>@Resource.ReplyFor:</h2>
        <div class="display-label">
          @MessagesAndNotes.From  <b>@Html.DisplayFor(model => model.Parent.Author.UserName) </b>
        </div>
        <div class="display-label">
         <b>@Html.DisplayFor(model => model.Parent.SentDate)</b>
        </div>
        <div class="display-field">
            @Html.DisplayFor(model => model.Parent.Title)
        </div>

        <div class="display-field">
            @Html.DisplayFor(model => model.Parent.Text)
        </div>

    </div>
@using (Html.BeginForm("Reply", "Message", FormMethod.Post, new { @class = "form-horizontal", role = "form"})) 
{
    @Html.AntiForgeryToken()
    
        @Html.ValidationSummary(true)
        @Html.HiddenFor(model => model.SentDate)
         @Html.HiddenFor(model => model.AuthorId)
       @Html.HiddenFor(model => model.AddresseeId)
       @Html.HiddenFor(model => model.ParentId)
        <div class="form-group">
            <div class="editor-label">
            @Html.LabelFor(model => model.Title)
                </div>
            <div class="editor-field">
                @Html.EditorFor(model => model.Title)
                @Html.ValidationMessageFor(model => model.Title)
            </div>
        </div>

        <div class="form-group">
            <div class="editor-label">
            @Html.LabelFor(model => model.Text)
                </div>
            <div class="editor-field">
                @Html.EditorFor(model => model.Text)
                @Html.ValidationMessageFor(model => model.Text)
            </div>
        </div>

        <div class="form-group">
            <div class="button-wrapper">
                <input type="submit" value="@MessagesAndNotes.SendMessage" class="sub-button"/>
            </div>
        </div>

}
<p class="links" style="width:100%">
    @Html.ActionLink(@Resource.Back, "Browse", "UserProfile", new{id=Model.AddresseeId}, null)
</p>

</div>
</div>

MyArtGallery/Views/Message/Send.cshtml
@model MyArtGallery.Models.Message
@using MyArtGallery.Resources;
@{
    ViewBag.Title = @MessagesAndNotes.SendMessage;
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<div id="gallery-wrapper">
<div id="form-wrapper">
<h2>@MessagesAndNotes.SendMessage</h2>
<p>@MessagesAndNotes.From: @Model.AuthorId - @MessagesAndNotes.To: @Model.AddresseeId</p>
@using (Html.BeginForm("Send", "Message", FormMethod.Post, new { @class = "form-horizontal", role = "form"})) 
{
    @Html.AntiForgeryToken()
    
        @Html.ValidationSummary(true)
        @Html.HiddenFor(model => model.SentDate)
         @Html.HiddenFor(model => model.AuthorId)
       @Html.HiddenFor(model => model.AddresseeId)
        <div class="form-group">
            <div class="editor-label">
            @Html.LabelFor(model => model.Title)
                </div>
            <div class="editor-field">
                @Html.EditorFor(model => model.Title)
                @Html.ValidationMessageFor(model => model.Title)
            </div>
        </div>

        <div class="form-group">
            <div class="editor-label">
            @Html.LabelFor(model => model.Text)
                </div>
            <div class="editor-field">
                @Html.EditorFor(model => model.Text)
                @Html.ValidationMessageFor(model => model.Text)
            </div>
        </div>

        <div class="form-group">
            <div class="button-wrapper">
                <input type="submit" value="@MessagesAndNotes.SendMessage" class="sub-button"/>
            </div>
        </div>
}

<ul class="links">
    <li>@Html.ActionLink(@Resource.Back, "Browse", "UserProfile", new{id=Model.AddresseeId}, null)</li>
</ul>
</div>
</div>

MyArtGallery/Views/Message/SentList.cshtml
@model PagedList.IPagedList<MyArtGallery.Models.Message>
@using PagedList.Mvc;
@using MyArtGallery.Resources;
@{
    ViewBag.Title = @MessagesAndNotes.Messages;
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>@MessagesAndNotes.Messages</h2>
      @if (Model.Count() == 0)
      {
          <p>@MessagesAndNotes.NoMessages</p>
     }
<table id="message-list">
   
@foreach (var item in Model) {
    <tr>
        <td class="author-name">
                  <b>@Html.DisplayFor(modelItem => item.Author.UserName)</b>
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Title)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Text)
            @Html.ActionLink(@Resource.Browse, "Details", new { id=item.MessageId })
     
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.SentDate)
        </td>
    </tr>
}

</table>
<div id="pager">
@Resource.Page @(Model.PageCount < Model.PageNumber ? 0 : Model.PageNumber) @Resource.Of @Model.PageCount

@Html.PagedListPager(Model, page => Url.Action("SentList", new { page }), new PagedListRenderOptions{
                                                                        LinkToFirstPageFormat = "<<",
                                                                        LinkToPreviousPageFormat =@Resource.Prev,
                                                                        LinkToNextPageFormat = @Resource.Next,
                                                                        LinkToLastPageFormat = ">>",

                                                              })
</div>
<ul class="links">
<li>@Html.ActionLink(@MessagesAndNotes.ReceivedMessages, "ReceivedList")</li>
</ul>