MyArtGallery/Models/Notification.cs
using MyArtGallery.Resources;
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Web;

namespace MyArtGallery.Models
{
    public enum NoteType
    {
        [Display(Name = "FavouritedNote", ResourceType = typeof(MessagesAndNotes))]
        Favourited = 1,
        [Display(Name = "CommentNote", ResourceType = typeof(MessagesAndNotes))]
        Comment,
        [Display(Name = "CommentRateNote", ResourceType = typeof(MessagesAndNotes))]
        CommentRated,
        [Display(Name = "ReplyNote", ResourceType = typeof(MessagesAndNotes))]
        CommentReply,
        [Display(Name = "EditedCommentNote", ResourceType = typeof(MessagesAndNotes))]
        EditedComment,
        [Display(Name = "DeletedCommentNote", ResourceType = typeof(MessagesAndNotes))]
        DeletedComment,
        [Display(Name = "DeletedImageNote", ResourceType = typeof(MessagesAndNotes))]
        DeletedImage,
        [Display(Name = "EditedImageNote", ResourceType = typeof(MessagesAndNotes))]
        EditedImage,
        [Display(Name = "RightsChanged", ResourceType = typeof(MessagesAndNotes))]
        RightsChanged
    };
    public class Notification
    {
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        public int NotificationId { get; set; }
        //jakiego obrazka lub komentarza dotyczy
        public int ThingId { get; set; }
        //od kogo
        public string UserId { get; set; }
        //do kogo
        public string AddresseeId { get; set; }
        [StringLength(500)]
        [Display(Name = "Text", ResourceType = typeof(Resource))]
        public string Text { get; set; }
        [Display(Name = "MessageDate", ResourceType = typeof(MessagesAndNotes))]
        [DataType(DataType.Date)]
        public DateTime SentDate { get; set; }
        [Display(Name = "WasRead", ResourceType = typeof(MessagesAndNotes))]
        public bool WasRead { get; set; }
        public NoteType Kind { get; set; }
    }
}

MyArtGallery/Controllers/CommentController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using MyArtGallery.Models;
using Microsoft.AspNet.Identity;
using Microsoft.AspNet.Identity.EntityFramework;
using MyArtGallery.Repositories;
using System.Threading.Tasks;
using MyArtGallery.Models.GalleryViewModels;
using MyArtGallery.Resources;
using PagedList;
using MyArtGallery.App_Start;

namespace MyArtGallery.Controllers
{
    public class CommentController : BasicController
    {
        private MyArtGalleryContext context;
        private ICommentRepository commentrepo;
        private INoteRepository noterepository;
        public UserManager<UserProfile> UserManager { get; private set; }
        public CommentController()
        {
            this.context = new MyArtGalleryContext();
            UserManager = new UserManager<UserProfile>(new UserStore<UserProfile>(context));
            commentrepo = new CommentRepository(context);
            noterepository = new NoteRepository(context);
        }

        public ActionResult ListByAuthor(string username, int? page)
        {
            IQueryable<Comment> comments = commentrepo.ListComments(username).OrderByDescending(c=>c.AddedDate);
            int pagenumber = (page ?? 1);
            ViewBag.Author = username;
            ViewBag.CanEdit = false;
            UserProfile user = UserManager.FindByName(User.Identity.Name);
            if (!UserManager.IsInRole(user.Id, "Banned") && (user.UserName).Equals(username))
                ViewBag.CanEdit = true;
            else if(UserManager.IsInRole(user.Id, "Admin") || UserManager.IsInRole(user.Id, "Moderator"))
                ViewBag.CanEdit = true;
            return View(comments.ToPagedList(pagenumber, 25));
        }

        public ActionResult ListByPicture(int id, int? page)
        {
            IQueryable<Comment> comments = commentrepo.ListComments(id);
            ViewBag.CanEdit = false;
            UserProfile user = UserManager.FindByName(User.Identity.Name);
            if (UserManager.IsInRole(user.Id, "Admin") || UserManager.IsInRole(user.Id, "Moderator"))
                ViewBag.CanEdit = true;
            int pagenumber = (page ?? 1);
            ViewBag.PictureId = id;
            return View(comments.ToPagedList(pagenumber, 10));
        }

        public async Task<ActionResult> Details(int? id)
        {
            if (id == null)
                return RedirectToAction("Error", "Home", new ErrorViewModel { Message = Errors.CommentNotFound });
           
            Comment comment = await commentrepo.getCommentAsync((int)id);
            if (comment == null)
                return RedirectToAction("Error", "Home", new ErrorViewModel { Message=Errors.CommentNotFound});
            Comment parent = null;
            if(comment.ParentId!=null)
                parent = await commentrepo.getCommentAsync((int)comment.ParentId);

            ViewBag.Parent = false;
            if (parent != null)
                ViewBag.Parent = true;
            ViewBag.CanEdit = false;
            UserProfile user = await UserManager.FindByNameAsync(User.Identity.Name);
            if (UserManager.IsInRole(user.Id, "Admin") || UserManager.IsInRole(user.Id, "Moderator") || comment.UserName.Equals(User.Identity.Name))
                ViewBag.CanEdit = true;
            //if (user.Rank.Equals(Rank.Admin) || user.Rank.Equals(Rank.Moderator) || comment.UserName.Equals(User.Identity.Name))
            //    ViewBag.CanEdit = true;
            return View(comment);
        }
        
        [MyAuthenticationFilter]
        public ActionResult Comment(int? id)
        {
            if (id == null)
                return PartialView("Confirm", new ActionConfirmViewModel { Message = Errors.PictureNotFound, Success = false });
            UserProfile user = UserManager.FindByName(User.Identity.Name);
            if (UserManager.IsInRole(user.Id, "Banned"))
                return PartialView("Confirm", new ActionConfirmViewModel { Message = Errors.BannedUser, Success = false });
            AddCommentViewModel model = new AddCommentViewModel();
            model.PictureId = (int) id;
            model.UserProfileId = User.Identity.Name;
         
            return PartialView(model);
        }

        [HttpPost]
        public async Task<ActionResult> Comment(AddCommentViewModel model)
        {
            if (ModelState.IsValid)
            {
                Comment comment = new Comment { Text = model.Text, PictureId = model.PictureId, UserName = model.UserProfileId };
                if (await commentrepo.AddComment(comment) != null)
                {
                    Picture pic = await (new PictureRepository()).getPictureAsync(model.PictureId);
                    if (!(pic.UserName).Equals(User.Identity.Name))
                    {
                        //nie dostajesz powiadomienia, jak komentujesz swoje obrazy
                        Notification note = new Notification { ThingId = model.PictureId, UserId = User.Identity.Name, AddresseeId = pic.UserName, SentDate = DateTime.Now, Kind = NoteType.Comment, Text = User.Identity.Name + " " + MessagesAndNotes.CommentNote, WasRead = false };
                        await noterepository.AddNote(note);
                    }
                    return PartialView("Confirm", new ActionConfirmViewModel { Message = CommentOptions.CommentAdded, Success = true });
           
                }
            }

            return PartialView(model);
        }

        [MyAuthenticationFilter]
        public ActionResult Reply(int? id)
        {
            if(id==null)
                return PartialView("Confirm", new ActionConfirmViewModel { Message = Errors.CommentNotFound, Success = false });
            UserProfile user = UserManager.FindByName(User.Identity.Name);
            if (UserManager.IsInRole(user.Id, "Banned"))
                return PartialView("Confirm", new ActionConfirmViewModel { Message = Errors.BannedUser, Success = false });
           
            AddCommentViewModel model = new AddCommentViewModel();
            Comment parent = commentrepo.getComment((int)id);
            if (parent == null)
                return PartialView("Confirm", new ActionConfirmViewModel { Message = Errors.CommentNotFound, Success = false });
            model.ParentId = parent.CommentId;
            model.PictureId = parent.PictureId;
            model.UserProfileId = User.Identity.Name;
            ViewBag.Parent = parent;
            return PartialView(model);
        }

        [HttpPost]
        public async Task<ActionResult> Reply(AddCommentViewModel model)
        {
            Comment parent = commentrepo.getComment(model.ParentId);
            if (ModelState.IsValid)
            {
                Comment comment = new Comment { Text=model.Text, UserName=model.UserProfileId, ParentId=model.ParentId, PictureId=model.PictureId};
                await commentrepo.AddComment(comment);
                if (!(parent.Picture.UserName).Equals(User.Identity.Name))
                {
                    Notification note = new Notification { ThingId = model.ParentId, UserId = model.UserProfileId, AddresseeId = parent.UserName, SentDate = DateTime.Now, Kind = NoteType.CommentReply, Text = model.UserProfileId + " " + MessagesAndNotes.ReplyNote, WasRead = false };
                    await noterepository.AddNote(note);
                }
                return PartialView("Confirm", new ActionConfirmViewModel { Message = CommentOptions.CommentAdded, Success = true });
           
            }
            ViewBag.Parent = parent;
            return PartialView(model);
        }

        // GET: /Comment/Edit/5
        public async Task<ActionResult> Edit(int? id)
        {
            
            if (id == null)
                return PartialView("Confirm", new ActionConfirmViewModel { Message = Errors.CommentNotFound, Success = false });
            Comment comment = commentrepo.getComment((int)id);
            if (comment == null)
                return PartialView("Confirm", new ActionConfirmViewModel { Message = Errors.CommentNotFound, Success = false });       
            UserProfile logged = await UserManager.FindByNameAsync(User.Identity.Name);
            if (!(comment.UserName).Equals(User.Identity.Name) && UserManager.IsInRole(logged.Id, "User"))
                return PartialView("Confirm", new ActionConfirmViewModel { Message = Errors.PrivacyViolation, Success = false });
            if (UserManager.IsInRole(logged.Id, "Banned"))
                return PartialView("Confirm", new ActionConfirmViewModel { Message = Errors.BannedUser, Success = false });
           
            return PartialView(comment);
        }


        [HttpPost]
        public async Task<ActionResult> Edit(Comment model)
        {
            if (ModelState.IsValid)
            {
                Comment comment = await commentrepo.getCommentAsync(model.CommentId);
                comment.Text = model.Text;
                await commentrepo.EditComment(comment);
                if (!(User.Identity.Name).Equals(comment.UserName))
                {
                    Notification note = new Notification { AddresseeId = comment.UserName, SentDate = DateTime.Now, WasRead = false, Kind = NoteType.EditedComment, UserId = User.Identity.Name, Text = MessagesAndNotes.EditedCommentNote, ThingId = comment.CommentId };
                    await noterepository.AddNote(note);
                }
                return PartialView("Confirm", new ActionConfirmViewModel { Message = CommentOptions.CommentEdited, Success = true });
           
            }
            return PartialView(model);
        }


        // GET: /Comment/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)

MyArtGallery/Controllers/NotificationController.cs
using Microsoft.AspNet.Identity;
using Microsoft.AspNet.Identity.EntityFramework;
using MyArtGallery.Models;
using MyArtGallery.Repositories;
using MyArtGallery.Models.UserViewModels;
using MyArtGallery.Resources;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;
using PagedList;
using MyArtGallery.App_Start;

namespace MyArtGallery.Controllers
{
    public class NotificationController : BasicController
    {
        private INoteRepository notificationrepo;
        public UserManager<UserProfile> UserManager { get; private set; }
        public NotificationController(UserManager<UserProfile> userManager, NoteRepository repo)
        {
            UserManager = userManager;
            notificationrepo = repo;
        }

        public NotificationController()
            : this(new UserManager<UserProfile>(new UserStore<UserProfile>(new MyArtGalleryContext())), new NoteRepository())
        {
        }

        [MyAuthenticationFilter]
        public ActionResult UserNotifications(int? page)
        {
            IQueryable<Notification> notes = notificationrepo.ReceivedNotes(User.Identity.Name).AsQueryable().OrderByDescending(n=>n.SentDate);
            int pagenumber = (page ?? 1);
            return View(notes.ToPagedList(pagenumber, 20));
        }

        [MyAuthenticationFilter]
        public ActionResult ChooseType()
        {
            MessageTypeViewModel model = new MessageTypeViewModel();
            
            return PartialView(model);
        }

        [MyAuthenticationFilter]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult NotesByType(MessageTypeViewModel model)
        {
            List<Notification> notes = notificationrepo.ReceivedByType(User.Identity.Name, (int)model.Type).ToList();
            return View(notes);
        }

        [MyAuthenticationFilter]
        public ActionResult NotesByAuthor(string id)
        {
            List<Notification> notes = notificationrepo.ReceivedByAuthor(User.Identity.Name, id).ToList();

            return View(notes);
        }

        [MyAuthenticationFilter]
        public async Task<ActionResult> Details(int? id)
        {
            if (id == null)
                return RedirectToAction("Error", "Home", new { message=Errors.MessageNotFound});
            Notification note = await notificationrepo.getNotification((int)id);
            if (note==null)
                return RedirectToAction("Error", "Home", new { message = Errors.MessageNotFound });
            if (!note.AddresseeId.Equals(User.Identity.Name))
                return RedirectToAction("Error", "Home", new { message = Errors.PrivacyViolation });
            await notificationrepo.SignAsRead(note);
           
           
            return View(note);
        }

        
	}
}

MyArtGallery/Views/Notification/ChooseType.cshtml
@model MyArtGallery.Models.UserViewModels.MessageTypeViewModel
@using MyArtGallery.Resources;
@using (Html.BeginForm("NotesByType", "Notification", FormMethod.Post, new { @class = "form-small", role = "form"})) 
{
    @Html.AntiForgeryToken()
        @Html.ValidationSummary(true)
        <div class="form-group">
            <div class="button-wrapper">
                   @Html.EnumDropDownListFor(model => model.Type)
                <input type="submit" value="@Resource.Filter" class="sub-button" />
            </div>
</div>
}

MyArtGallery/Views/Notification/Details.cshtml
@model MyArtGallery.Models.Notification
@using MyArtGallery.Resources;
@{
    ViewBag.Title = @MessagesAndNotes.Message;
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div>
    <div class="message-frame">

        <div>
         @MessagesAndNotes.From <b>@Html.DisplayFor(model => model.UserId) </b>
        </div>
        <div>
          @Html.DisplayFor(model => model.Text)
        </div>
        <div>
          <i>@Html.DisplayFor(model => model.SentDate)</i>
        </div>

        <div>
           @if((int)(Model.Kind)==2 || (int)(Model.Kind)==3 || (int)(Model.Kind)==4 || (int)(Model.Kind)==5 || (int)(Model.Kind)==6){
            <p>@Html.ActionLink(@Resource.Go, "Details", "Comment", new { id=Model.ThingId }, new { @class = "links" })</p>
           }
           else if((int)(Model.Kind)==9)
           {}
           else{
            <p>@Html.ActionLink(@Resource.Go, "Details", "Picture", new { id=Model.ThingId }, new { @class = "links" })</p>
           }
        </div>
   </div>
</div>
<ul class="links">
 <li>@Html.ActionLink(@Resource.Back, "Notifications", "UserProfile", new {id = User.Identity.Name}, null)</li>

</ul>

MyArtGallery/Views/Notification/NotesByType.cshtml
@model IEnumerable<MyArtGallery.Models.Notification>
@using MyArtGallery.Resources;
@{
    ViewBag.Title = @MessagesAndNotes.Notifications;
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>@MessagesAndNotes.Notifications</h2>
      @if (Model.Count() == 0)
      {
          <p>@MessagesAndNotes.NoNotes</p>
     }
<table id="note-list">
@foreach (var item in Model) {
    <tr>
        <td class="author-name">
                   @if(item.WasRead==false){
             <b class="highlight">*</b>
           }
                  @Html.DisplayFor(modelItem => item.UserId)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Text)
            @Html.ActionLink(@Resource.Browse, "Details", new { id=item.NotificationId })
     
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.SentDate)
        </td>
    </tr>
}

</table>
<ul class="links">
<li> @Html.ActionLink(@Resource.Back, "Notifications", "UserProfile", new {id = User.Identity.Name}, null)</li>

</ul>

MyArtGallery/Views/Notification/UserNotifications.cshtml
@model PagedList.IPagedList<MyArtGallery.Models.Notification>
@using PagedList.Mvc;
@using MyArtGallery.Resources;
@{
    ViewBag.Title = @MessagesAndNotes.Notifications;
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>@MessagesAndNotes.Notifications</h2>
      @if (Model.Count() == 0)
      {
          <p>@MessagesAndNotes.NoNotes</p>
     }
<table id="note-list">
   <tr>
    <td></td>
    <td> @{Html.RenderAction("ChooseType", "Notification");}</td>
    <td></td>
   </tr>
@foreach (var item in Model) {
    
    <tr>
        <td class="author-name">
               @if(item.WasRead==false){
             <b class="highlight">*</b>
           }
               @Html.DisplayFor(modelItem => item.UserId)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Text)
            @Html.ActionLink(@Resource.Browse, "Details", new { id=item.NotificationId })
     
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.SentDate)
        </td>
    </tr>
}

</table>
<div id="pager">
@Resource.Page @(Model.PageCount < Model.PageNumber ? 0 : Model.PageNumber) @Resource.Of @Model.PageCount

@Html.PagedListPager(Model, page => Url.Action("UserNotifications", new { page }), new PagedListRenderOptions{
                                                                        LinkToFirstPageFormat = "<<",
                                                                        LinkToPreviousPageFormat = @Resource.Prev,
                                                                        LinkToNextPageFormat = @Resource.Next,
                                                                        LinkToLastPageFormat = ">>",

                                                              })
</div>
<ul class="links">
    <li>@Html.ActionLink(@Resource.Back, "Index", "Home")</li>
</ul>