MyArtGallery/Models/Favourite.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Web;

namespace MyArtGallery.Models
{
    public class Favourite
    {
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        public int FavouriteId { get; set; }
        [ForeignKey("User")]
        public string UserName { get; set; }
        public virtual UserProfile User { get; set; }
        [ForeignKey("Image")]
        public int PictureId { get; set; }
        public virtual Picture Image { get; set; }

    }
}

MyArtGallery/Models/GalleryViewModels/DownloadViewModel.cs
using MyArtGallery.Resources;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MyArtGallery.Models.GalleryViewModels
{
    public class DownloadViewModel
    {
        public int Id { get; set; }
        [Display(Name = "Sizes", ResourceType = typeof(ImageOptions))]
        public int Size { get; set; }
        public IEnumerable<SelectListItem> Sizes { get; set; }
    }
}

MyArtGallery/Controllers/CategoryController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using MyArtGallery.Models;
using MyArtGallery.Repositories;
using System.Threading.Tasks;
using PagedList;
using MyArtGallery.Resources;

namespace MyArtGallery.Controllers
{
    public class CategoryController : BasicController
    {
        private ICategoryRepository cat_repo;
        public CategoryController()
            : this(new CategoryRepository())
        {}
         public CategoryController(ICategoryRepository repository)
        {
            cat_repo = repository;
        }
        // GET: /Category/
        public async Task<ActionResult> Index()
        {
            var categories = cat_repo.Categories();
            string lang = RouteData.Values["culture"] as string;
            ViewBag.Language = lang;
            return View(await categories.ToListAsync());
        }

        public ActionResult StartList()
        {
            var categories = cat_repo.MainCategories();

            return View(categories.ToList());
        }

        
        public async Task<ActionResult> Images(int? id, int? page)
        {
            if (id == null)
                return RedirectToAction("Error", "Home", new { message = Errors.NoSuchGenre });

            Category category = await cat_repo.GetCategory(id);
            if (category == null)
                return RedirectToAction("Error", "Home", new { message = Errors.NoSuchGenre });
            IQueryable<Picture> pictures = category.Pictures.AsQueryable().OrderByDescending(p=>p.LastModifiedDate);
            int pagenumber = (page ?? 1);
            ViewBag.Category = category;
            string lang = RouteData.Values["culture"] as string;
            ViewBag.Language = lang;
            return View(pictures.ToPagedList(pagenumber,12));
        }
    }
}

MyArtGallery/Controllers/PictureController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using MyArtGallery.Models;
using Microsoft.AspNet.Identity;
using MyArtGallery.Repositories;
using Microsoft.AspNet.Identity.EntityFramework;
using MyArtGallery.Services;
using MyArtGallery.Validation;
using System.Threading.Tasks;
using MyArtGallery.Models.GalleryViewModels;
using System.Web.Helpers;
using System.Drawing;
using MyArtGallery.Models.Helpers;
using MyArtGallery.Resources;
using System.Text;
using MyArtGallery.Helpers;
using PagedList;
using System.IO;
using System.Drawing.Imaging;
using MyArtGallery.App_Start;

namespace MyArtGallery.Controllers
{
    public class PictureController : BasicController
    {
        private IImageService imageservice;
        public PictureController()
        {
            imageservice = new ImageService(new ModelStateExtension(this.ModelState));
        }


        public PictureController(IImageService s)
        {
            imageservice = s;
        }
        // GET: /Picture/
        public async Task<ActionResult> Index()
        {
            var pictures = imageservice.Pictures();
            return View(await pictures.ToListAsync());
        }

        public ActionResult ListByAuthor(string id, int? page)
        {
            var pictures = imageservice.Pictures(id).OrderByDescending(p=>p.LastModifiedDate);
            ViewBag.Author = id;

            int pagenumber = (page ?? 1);
            return View(pictures.ToPagedList(pagenumber,20));
        }
        public ActionResult Featured(string id)
        {
            IQueryable<Picture> model = imageservice.Pictures(id, 9);
            return View(model.ToList());
        }
        // GET: /Picture/Details/5
        public async Task<ActionResult> Details(int? id)
        {
            if (id == null)
                return RedirectToAction("Error", "Home", new { message = Errors.PictureNotFound });
            Picture picture = await imageservice.GetPictureAsync((int)id);
            if (picture == null)
                return RedirectToAction("Error", "Home", new { message = Errors.PictureNotFound });
            if ((!picture.Public || picture.Adult) && !Request.LogonUserIdentity.IsAuthenticated)
                return RedirectToAction("Login", "UserProfile", new { message = Errors.LoginRequired });
            UserProfile user = await imageservice.GetUser(User.Identity.Name);
            ViewBag.CanEdit = false;
            bool admin=await imageservice.CheckRole(user.Id, "Admin");
            bool mod = await imageservice.CheckRole(user.Id, "Moderator");
            if (admin|| mod || picture.UserName.Equals(User.Identity.Name))
                ViewBag.CanEdit = true;
            
            if(picture.Adult && UserProfileHelper.CountUserAge(user.BirthDate)<18)
                return RedirectToAction("Error", "Home", new { message = Errors.TooYoung });
            string lang = RouteData.Values["culture"] as string;
            ViewBag.Language = lang;
            return View(picture);
        }

        public async Task<ActionResult> FullSize(int? id)
        {
            if (id == null)
                return RedirectToAction("Error", "Home", new { message = Errors.PictureNotFound });
            Picture picture = await imageservice.GetPictureAsync((int)id);
            if (picture == null)
                return RedirectToAction("Error", "Home", new { message = Errors.PictureNotFound });
            if ((!picture.Public || picture.Adult) && !Request.LogonUserIdentity.IsAuthenticated)
                return RedirectToAction("Login", "UserProfile", new { message = Errors.LoginRequired });
            UserProfile user = await imageservice.GetUser(User.Identity.Name);
            if (picture.Adult && UserProfileHelper.CountUserAge(user.BirthDate) < 18)
                return RedirectToAction("Error", "Home", new { message = Errors.TooYoung });
            return View(picture);
        }

        [MyAuthenticationFilter]
        public async Task<ActionResult> Favourite(int? id)
        {
            if (id == null)
                return PartialView("Confirm", new ActionConfirmViewModel { Message = Errors.PictureNotFound, Success = false });
            Picture picture = imageservice.GetPicture((int)id);
            if (picture == null)
                return PartialView("Confirm", new ActionConfirmViewModel { Message = Errors.PictureNotFound, Success = false });
            string name = User.Identity.Name;
            UserProfile user = await imageservice.GetUser(name);
            
            if (user.Favourites.AsQueryable().Where(f=>f.PictureId==picture.PictureId).Count()==0)
            {
                Favourite fav = new Favourite { UserName = name, PictureId = picture.PictureId };

                picture.Favourites += 1;
                await imageservice.EditPictureInfo(picture);
                await imageservice.AddFavourite(fav);
            }
            //jak obraz jest już w twoich ulubionych - nic się nie dzieje
            Notification note = new Notification { ThingId = picture.PictureId, UserId = user.UserName, AddresseeId = picture.UserName, SentDate = DateTime.Now, Kind = NoteType.Favourited, Text = user.UserName + " " + MessagesAndNotes.FavouritedNote, WasRead = false };
            await imageservice.AddNote(note);
            return PartialView("Confirm", new ActionConfirmViewModel {  Message=MessagesAndNotes.YouFavouritedNote, Success=true});
        }
        
        public ActionResult Favourites(int? page, int? id)
        {
            if (id == null)
                return RedirectToAction("Error", new {  message = Errors.PictureNotFound });
            Picture picture = imageservice.GetPicture((int)id);
            if (picture == null)
                return RedirectToAction("Error", new { message = Errors.PictureNotFound });
            ViewBag.PictureName = picture.Title;
            ViewBag.PictureId = picture.PictureId;
            ViewBag.Author = picture.UserName;
            int pagenumber = (page ?? 1);
            IQueryable<Favourite> favs = picture.Favourited.AsQueryable().OrderByDescending(f => f.FavouriteId);

            return View(favs.ToPagedList(pagenumber, 25));
        }
        public async Task<ActionResult> DeleteFav(int? id)
        {
            if (id == null)
                return RedirectToAction("Error", "Home", new { message = Errors.PictureNotFound });
            
            await imageservice.DeleteFav((int)id);
            return RedirectToAction("Favourites", "UserProfile", new { id = User.Identity.Name });

        }
        public ActionResult Download(int id)
        {
            DownloadViewModel model = new DownloadViewModel();
            model.Id = id;
            Dictionary<int,string> sizes = new Dictionary<int,string>();
            Picture picture = imageservice.GetPicture(id);
            sizes.Add(1, ImageOptions.FullSize);
            if (picture.Height > 800 || picture.Width > 800)
            {
                sizes.Add(2, ImageOptions.MediumSize);
            }
            sizes.Add(3, ImageOptions.Thumbnail);
            
            model.Sizes = ImageHelper.Sizes(sizes);
            return View(model);
        }

        [MyAuthenticationFilter]
        [HttpPost]
        public async Task<FileResult> Download(DownloadViewModel model)
        {
            Picture picture = await imageservice.GetPictureAsync(model.Id);
            DeleteTemps(User.Identity.Name);
            string p;
            if (model.Size == 1)
                p = picture.FullSizeUrl;
            else if (model.Size == 3)
                p = picture.ThumbnailUrl;
            else
                p = picture.Url;
            picture.Downloads += 1;
            string tempPath="";
            await imageservice.EditPictureInfo(picture);
            if(ImageHelper.GetFileType(picture.FullSizeUrl).ToLower().Equals(".gif")){
                return File(p, "image/gif", picture.Title + ".gif");
            }
            else{
            tempPath =  ImageHelper.TemporaryPath(User.Identity.Name, ImageHelper.GetFileType(picture.FullSizeUrl));
            Image img = Image.FromFile(Request.MapPath(p));
            img.Save(Request.MapPath(tempPath));
            string downloadPath = ImageHelper.SetImageProperties(picture, Request.MapPath(tempPath), Request.MapPath(ImageHelper.TemporaryPath(User.Identity.Name, ImageHelper.GetFileType(tempPath))));
            return File(downloadPath, "image/jpeg", picture.Title + ".jpg");
            }
        } 

        //dodajemy do albumu
        [MyAuthenticationFilter]
        [CheckIfBanned]
        public async Task<ActionResult> Add(int id)
        {
            
            Album a = await imageservice.GetAlbum(id);
            if (a==null)
                return RedirectToAction("Error", "Home", new { message = Errors.AlbumNotFound });
            DeleteTemps(User.Identity.Name);
            AddPictureViewModel model = new AddPictureViewModel();
            model.AlbumId = id;
            model.UserProfileId = User.Identity.Name;
            string culture = RouteData.Values["culture"] as string;
            model.Categories = imageservice.CategoriesSelect(culture);
            return View(model);
        }

    
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Add(AddPictureViewModel model)
        {
            string[] paths = new string[3];
            CreateFolder(User.Identity.Name);
            string proto_path = @"~/Images/" + User.Identity.Name + "/Temp/";
            Image img = null;
            string ext = "";
            bool validType = false;
            if (model.IsUrl)
            {
                if (model.Url != null)
                {
                    validType = imageservice.UrlValidation(model.Url);
                    if (validType)

MyArtGallery/Controllers/TagController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Threading.Tasks;
using System.Net;
using System.Web;
using System.Web.Mvc;
using MyArtGallery.Models;
using MyArtGallery.Repositories;
using MyArtGallery.Resources;
using PagedList;
using Microsoft.AspNet.Identity;
using Microsoft.AspNet.Identity.EntityFramework;
using MyArtGallery.App_Start;

namespace MyArtGallery.Controllers
{
    public class TagController : BasicController
    {
        ITagRepository tag_repo;
        private UserManager<UserProfile> usermanager;
        public TagController()
            : this(new TagRepository())
        {}
         public TagController(ITagRepository repository)
        {
            tag_repo = repository;
            usermanager = new UserManager<UserProfile>(new UserStore<UserProfile>(new MyArtGalleryContext()));
            
        }
        
        public ActionResult AllTags(int? page)
        {
            //alfabetycznie!
            IQueryable<Tag> tags = tag_repo.Tags().OrderBy(t=>t.Name);
            int pageSize = 100;
            int pageNumber = (page ?? 1);
            return View(tags.ToPagedList(pageNumber, pageSize));
        }

        
        public async Task<ActionResult> Images(int? id, int? page)
        {
            if (id == null)
                return RedirectToAction("Error", "Home", new { message = Tagging.TagNotFound });
            Tag tag = await tag_repo.getTag(id);
            if(tag==null)
                return RedirectToAction("Error", "Home", new { message = Tagging.TagNotFound });
            ViewBag.TagName = tag.Name;
            ViewBag.Id = tag.TagId;
            IQueryable<Picture> pictures = tag.Pictures.AsQueryable();
            pictures = pictures.OrderByDescending(p => p.LastModifiedDate);
            int pageSize = 20;
            int pageNumber = (page ?? 1);
            return View(pictures.ToPagedList(pageNumber, pageSize));
        }

        [MyAuthenticationFilter]
        [CheckIfBanned]
        public ActionResult NewTag()
        {
            Tag t = new Tag();
            return View(t);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> NewTag(Tag tag)
        {
            Tag test = await tag_repo.getTag(tag.Name);
            if (test != null)
                ModelState.AddModelError("Name", Tagging.TagNameError);
        
            if (ModelState.IsValid)
            {
                Tag t = new Tag();
                t.Name = tag.Name;
                t.Pictures = new List<Picture> { };
                await tag_repo.AddTag(t);
                return RedirectToAction("AllTags");
            }

            return View(tag);
        }

        [MyAuthenticationFilter]
        [RoleAuthorize("Admin", "Moderator")]
        public async Task<ActionResult> Edit(int? id)
        {
            if (id == null)
                return RedirectToAction("Error", "Home", Errors.NotFound);
            Tag tag = await tag_repo.getTag(id);
            if (tag == null)
                return RedirectToAction("Error", "Home", Tagging.TagNotFound);
            return View(tag);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Edit(Tag model)
        {
            Tag tag = await tag_repo.getTag(model.TagId);
            if (ModelState.IsValid)
            {
                if(model.Name!=null)
                   tag.Name = model.Name;
                await tag_repo.UpdateTag(tag);
                return RedirectToAction("AllTags");
            }
            return View(tag);
        }

    }
}

MyArtGallery/Views/Picture/Add.cshtml
@model MyArtGallery.Models.GalleryViewModels.AddPictureViewModel
@using MyArtGallery.Resources;
@{
    ViewBag.Title = @ImageOptions.AddImage;
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<div id="gallery-wrapper">
@using (Html.BeginForm("Add", "Picture", FormMethod.Post, new { @class = "image-editor", role = "form", enctype = "multipart/form-data" }))
{
<div id="form-wrapper">
    @Html.AntiForgeryToken()
    <h2>@ImageOptions.AddImage</h2>
        @Html.ValidationSummary(true)
         @Html.HiddenFor(model => model.UserProfileId)
        @Html.HiddenFor(model => model.AlbumId)
        @Html.HiddenFor(model => model.X)
        @Html.HiddenFor(model => model.Y)
        @Html.HiddenFor(model => model.Width)
        @Html.HiddenFor(model => model.Height)
       <div class="form-group">
		<div id="isurl" class="editor-label">
            @Html.LabelFor(model => model.Url)
			@Html.EditorFor(model => model.IsUrl)
		    <div id="imgurl">
			@Html.EditorFor(model => model.Url)
		    </div>
            @Html.ValidationMessageFor(model => model.Url)
		</div>
        
        
        </div>
        <div class="form-group">
         <div id="isfile" class="editor-label">
            @Html.LabelFor(model => model.File)
            @Html.EditorFor(model => model.IsFile)
		       <div id="imgfile">
			@Html.TextBoxFor(model => model.File, new { type = "file" })
		</div>  
            @Html.ValidationMessageFor(model => model.File)
		</div>
     
        </div>
        <div class="form-group">
            <div class="editor-label">
            @Html.LabelFor(model => model.Title)
                </div>
            <div class="editor-field">
                @Html.EditorFor(model => model.Title)
                @Html.ValidationMessageFor(model => model.Title)
            </div>
        </div>

        <div class="form-group">
            <div class="editor-label">
            @Html.LabelFor(model => model.Description)
                </div>
            <div class="editor-field">
                @Html.TextAreaFor(model => model.Description)
                @Html.ValidationMessageFor(model => model.Description)
            </div>
        </div>

        <div class="form-group">
            <div class="editor-label">
            @Html.LabelFor(model => model.Tags)
                </div>
            <div class="editor-field">
                @Html.EditorFor(model => model.Tags)
                @Html.ValidationMessageFor(model => model.Tags)
            </div>
        </div>


      <div class="form-group">
            <div class="editor-label">
              <b class="highlight">@ImageOptions.Category</b>
            </div>
            <div class="editor-field">
                 @Html.DropDownListFor(m => m.CategoryId, Model.Categories)
                @Html.ValidationMessageFor(model => model.CategoryId)
            </div>
        </div>
        <div class="form-group">
          @ImageEditorRes.GifMoving
       </div>
        <div class="form-group" id="animated">
          <div> @Html.LabelFor(model => model.Animated) </div>
            
			@Html.EditorFor(model => model.Animated)
       </div>
       <div class="form-group">
        @Html.LabelFor(model=> model.TurnAngle)<br />
        <hr />
        <div id="angles" class="editor-field">
         <label>@Html.RadioButtonFor(model => model.TurnAngle, 90) @ImageEditorRes.NinetyRight</label>
         <label>@Html.RadioButtonFor(model => model.TurnAngle, 270) @ImageEditorRes.NinetyLeft</label>
         <label>@Html.RadioButtonFor(model => model.TurnAngle, 180) @ImageEditorRes.HalfFullRight</label>      
         <label> @Html.RadioButtonFor(model => model.TurnAngle, 0) @ImageEditorRes.NoTurn</label>
        </div>
       </div>
      
        <div class="form-group">
            <div class="editor-label" id="fliphor">
         <label>  @Html.DisplayNameFor(model => model.MirrorHorizontal): </label>
         @Html.CheckBoxFor(model => model.MirrorHorizontal)
            </div>
        </div>

       <div class="form-group">
            <div class="editor-label" id="flipvert">
         <label>  @Html.DisplayNameFor(model => model.MirrorVertical): </label>
         @Html.CheckBoxFor(model => model.MirrorVertical)
            </div>
        </div>
        <div class="form-group">
            <div class="editor-label">
          <label>@Html.DisplayNameFor(model => model.Public): </label>
             @Html.CheckBoxFor(model => model.Public)
            </div>
        </div>

        <div class="form-group">
            <div class="editor-label">
           <label> @Html.DisplayNameFor(model => model.Adult): </label>
              @Html.CheckBoxFor(model => model.Adult)
            </div>
        </div>

        <div class="form-group">
            <div class="editor-label">
           <label>@Html.DisplayNameFor(model => model.CommentsOff):</label>
             @Html.CheckBoxFor(model => model.CommentsOff)
            </div>
        </div>

        <div class="form-group">
            <div class="button-wrapper">
                
                <input type="submit" value="@Resource.Add" id="picture-submit" class="sub-button"/>
            </div>
        </div>
<ul class="links" style="width:100%">
   <li> @Html.ActionLink(@Resource.Back, "Browse", "Album", new { id = Model.AlbumId }, null)</li>
</ul>
</div>
<div id="preview-wrapper">
<img alt="@ImageEditorRes.NotAnImage" id="preview" src="@Url.Content("~/Content/Images/background_pale.png")" />
</div>
}

</div>

@Scripts.Render("~/bundles/imageeditor")
@Scripts.Render("~/bundles/imageadder-button")

MyArtGallery/Views/Picture/Details.cshtml
@model MyArtGallery.Models.Picture
@using MyArtGallery.Models;
@using MyArtGallery.Resources;
@{
    ViewBag.Title = @Model.UserName+" - "+@Model.Title;
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<div id="profile-wrapper">
<div id="featured">
       <a class="photo-frame" href="@Url.Action("FullSize", "Picture", new { id = Model.PictureId })">
                 <img alt="@Model.Title" src="@Url.Content(Model.Url)"  title="@ImageOptions.ClickToFullSize"/>
           </a>
         <ul class="links">      
    @if(@Model.UserName==@User.Identity.Name){  
       <li>@Html.ActionLink(@ImageEditorRes.EditOrReplace, "EditImage",new { id=Model.PictureId }, null) </li>                 
   }
   else{    
    <li>@Html.ActionLink(@ImageOptions.Favourite, "Favourite", "Picture", new { id = Model.PictureId }, new{ @class="no-refresh"})</li> 
    <li>@Html.ActionLink(@Resource.MarkAsImproper, "MarkAsImproper", "Administration", new { id = Model.PictureId, kind=ProtestType.Picture }, new{ @class="no-refresh"})</li> 
   }
   @if(ViewBag.CanEdit)
   {
      <li>@Html.ActionLink(@ImageOptions.EditProperties, "EditData",new { id=Model.PictureId }, null) </li>
      <li>@Html.ActionLink(@Resource.Delete, "Delete", new { id=Model.PictureId }, null) </li>   
   }
<li>@Html.ActionLink(@Resource.Back, "Browse", "Album", new { path = Model.Album.Path }, null)</li>
</ul>
   @if(@Model.UserName==@User.Identity.Name){
  
     <div style="width:100%">
                @{Html.RenderAction("Move", "Picture", new{ id = Model.PictureId});}
            </div>}


<div id="comments-wrapper">
@if(!Model.CommentsOff){
     if(User.Identity.IsAuthenticated)
    {
    <div id="comment-menu" class="comment-menu">
     @Ajax.ActionLink(@CommentOptions.AddComment, "Comment", "Comment", new { id = Model.PictureId }, new AjaxOptions {UpdateTargetId = "comment-list"})

    </div>
    }
    <div id="comment-list">
       @{Html.RenderAction("ListByPicture", "Comment", new{ id = Model.PictureId});}
    </div>

}
else{
<h3>@CommentOptions.CommentsOff</h3>
}
</div>
    </div>

    <div id="info">
            <div class="display-field" id="details-header"><div id="author"> 
            <a href="@Url.Action("Browse", "UserProfile", new { id = Model.UserName })">
             <img alt="@Model.UserName" src="@Url.Content(Model.UserProfile.AvatarThumbPath)" />
            @Html.DisplayFor(model => model.UserName)</span></a>
            </div>
            <div id="title"> @Html.DisplayFor(model => model.Title)</div>
            </div>

            <div class="display-field" id="description">
             @Html.DisplayFor(model => model.Description)
            </div>


            <div class="display-label">
                @Html.DisplayNameFor(model => model.Category) : 

         
            <div class="display-field" id="category">
            @if(ViewBag.Language.Equals("pl")){
            if(Model.Category.ParentId!=null){
            <b>@Html.ActionLink(Model.Category.Parent.CategoryName, "Images", "Category", new { id=Model.Category.ParentId}, null) > </b> 
            }
             <b>    @Html.ActionLink(Model.Category.CategoryName, "Images", "Category", new { id=Model.Category.CategoryId}, null)</b>
            }
            else{
            if(Model.Category.ParentId!=null){
            <i>@Html.ActionLink(Model.Category.Parent.CategoryNameEn, "Images", "Category", new { id=Model.Category.ParentId}, null) > </i> 
            }
             <i>    @Html.ActionLink(Model.Category.CategoryNameEn, "Images", "Category", new { id=Model.Category.CategoryId}, null)</i>
            }
          
            </div>
            </div>

            <div class="display-label">
                @Html.DisplayNameFor(model => model.Tags):
                @foreach(Tag item in Model.Tags){
                   <b> @Html.ActionLink(item.Name, "Images", "Tag", new { id=item.TagId }, new{@class="links"})</b>       
                }
            </div>
           @if(Request.LogonUserIdentity.IsAuthenticated){
            <div>
               @{Html.RenderAction("Download", "Picture", new{ id = Model.PictureId});}

            </div>
            
           } 
           <hr />
            <div class="display-label">
              @Html.DisplayNameFor(model => model.AdditionDate) : 
            <div class="display-field">
              @Html.DisplayFor(model => model.AdditionDate)
            </div>
            </div>


            <div class="display-label">
              @Html.DisplayNameFor(model => model.LastModifiedDate) : 
            <div class="display-field">
              @Html.DisplayFor(model => model.LastModifiedDate)
            </div>
            </div>
            <div class="display-label">
              @Html.DisplayNameFor(model => model.Height)  x  @Html.DisplayNameFor(model => model.Width)
            <div class="display-field">
              @Html.DisplayFor(model => model.Height) x @Html.DisplayFor(model => model.Width)
            </div>
            </div>
            <div class="display-label">
              @Html.DisplayNameFor(model => model.FileSize) : 
            <div class="display-field">
              @Html.DisplayFor(model => model.FileSize)
            </div>
            </div>
            <hr />

             <div class="display-label">
              @Html.DisplayNameFor(model => model.CameraType) : 
            <div class="display-field">
              @Html.DisplayFor(model => model.CameraType)
            </div>
            </div>
            <div class="display-label">
              @Html.DisplayNameFor(model => model.Software) : 
            <div class="display-field">
              @Html.DisplayFor(model => model.Software)
            </div>
            </div>
            <div class="display-label">
              @Html.DisplayNameFor(model => model.DateTaken) : 
            <div class="display-field">
              @Html.DisplayFor(model => model.DateTaken)
            </div>
            </div>
            <div class="display-label">
              @Html.DisplayNameFor(model => model.Flash) : 
            <div class="display-field">
              @if(Model.Flash){
              @Resource.Yes;}
              else{
               @Resource.No;
              }
            </div>
            </div>
            <div class="display-label">
              @Html.DisplayNameFor(model => model.ExposureTime) : 
            <div class="display-field">
              @Html.DisplayFor(model => model.ExposureTime)
            </div>
            </div>
            <div class="display-label">
              @Html.DisplayNameFor(model => model.FocalLength) : 
            <div class="display-field">
               @if(Model.FocalLength!=null){
            <b>  @Html.DisplayFor(model => model.FocalLength) mm </b>
              }
            </div>
            </div>
            
            <div class="display-label">
              @Html.DisplayNameFor(model => model.ShutterSpd) : 
            <div class="display-field">
              @Html.DisplayFor(model => model.ShutterSpd)
            </div>
            </div>
            <div class="display-label">
              @Html.DisplayNameFor(model => model.Colours) : 
            <div class="display-field">
              @Html.DisplayFor(model => model.Colours)
            </div>
            </div>
             <div class="display-label">
               @ImageOptions.Favourited:   <b id="fav-count">@Html.ActionLink(@Model.Favourites.ToString(), "Favourites", "Picture", new { id=Model.PictureId }, null)</b>

            </div>
            <div>
            </div>
</div>

</div>